### ISSUE TITLE
very dark

### ISSUE THREAD

**Issue by substack** [royriojas/shell-executor#1]
The ansi colors don't look very good on a dark background:

![](http://scratch.substack.net/2015-07-03-125043_600x247_scrot.png)

Maybe this package doesn't need fancy colors at all?

**Comment by royriojas** [comment]
true, will add a ENV variable to disable coloring

**Comment by royriojas** [comment]
So In the end I removed the colored output completely. To enable it passing the option `--colored-output` should be enough.
